# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: ad55843aaacf1622fceba5a81e0f964ae6277726c86502f83b2de0d06edcb064469a464d0a69047985236e21373e7fe8f359d98a6fed563477e2ef0fdbbb9639

test:
  secret_key_base: 8887316c2f41c677a1852fc0f2e799b0c134c09127d1c4208a88b94358955ac663c4aa03f8d4ee3901e07d9c795a102c8479db5b79775bdf3e4c33f78f3291fd

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
